// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/entities/ihsg.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IHSGPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Open          float64                `protobuf:"fixed64,2,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,3,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,4,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,5,opt,name=close,proto3" json:"close,omitempty"`
	Volume        float64                `protobuf:"fixed64,6,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IHSGPoint) Reset() {
	*x = IHSGPoint{}
	mi := &file_pkg_entities_ihsg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IHSGPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IHSGPoint) ProtoMessage() {}

func (x *IHSGPoint) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_entities_ihsg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IHSGPoint.ProtoReflect.Descriptor instead.
func (*IHSGPoint) Descriptor() ([]byte, []int) {
	return file_pkg_entities_ihsg_proto_rawDescGZIP(), []int{0}
}

func (x *IHSGPoint) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *IHSGPoint) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *IHSGPoint) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *IHSGPoint) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *IHSGPoint) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *IHSGPoint) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type MarketDataset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Symbol        string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	FetchedAt     string                 `protobuf:"bytes,6,opt,name=fetchedAt,proto3" json:"fetchedAt,omitempty"`
	Data          []*IHSGPoint           `protobuf:"bytes,7,rep,name=data,proto3" json:"data,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,8,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketDataset) Reset() {
	*x = MarketDataset{}
	mi := &file_pkg_entities_ihsg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketDataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketDataset) ProtoMessage() {}

func (x *MarketDataset) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_entities_ihsg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketDataset.ProtoReflect.Descriptor instead.
func (*MarketDataset) Descriptor() ([]byte, []int) {
	return file_pkg_entities_ihsg_proto_rawDescGZIP(), []int{1}
}

func (x *MarketDataset) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MarketDataset) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MarketDataset) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MarketDataset) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MarketDataset) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *MarketDataset) GetFetchedAt() string {
	if x != nil {
		return x.FetchedAt
	}
	return ""
}

func (x *MarketDataset) GetData() []*IHSGPoint {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MarketDataset) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_pkg_entities_ihsg_proto protoreflect.FileDescriptor

const file_pkg_entities_ihsg_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/entities/ihsg.proto\x12\bentities\"\x87\x01\n" +
	"\tIHSGPoint\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x12\n" +
	"\x04open\x18\x02 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x03 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x04 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x05 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x01R\x06volume\"\xea\x01\n" +
	"\rMarketDataset\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1c\n" +
	"\tfetchedAt\x18\x06 \x01(\tR\tfetchedAt\x12'\n" +
	"\x04data\x18\a \x03(\v2\x13.entities.IHSGPointR\x04data\x12\"\n" +
	"\ferrorMessage\x18\b \x01(\tR\ferrorMessageB\x1bZ\x19ekel-backend/pkg/entitiesb\x06proto3"

var (
	file_pkg_entities_ihsg_proto_rawDescOnce sync.Once
	file_pkg_entities_ihsg_proto_rawDescData []byte
)

func file_pkg_entities_ihsg_proto_rawDescGZIP() []byte {
	file_pkg_entities_ihsg_proto_rawDescOnce.Do(func() {
		file_pkg_entities_ihsg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_entities_ihsg_proto_rawDesc), len(file_pkg_entities_ihsg_proto_rawDesc)))
	})
	return file_pkg_entities_ihsg_proto_rawDescData
}

var file_pkg_entities_ihsg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_entities_ihsg_proto_goTypes = []any{
	(*IHSGPoint)(nil),     // 0: entities.IHSGPoint
	(*MarketDataset)(nil), // 1: entities.MarketDataset
}
var file_pkg_entities_ihsg_proto_depIdxs = []int32{
	0, // 0: entities.MarketDataset.data:type_name -> entities.IHSGPoint
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_entities_ihsg_proto_init() }
func file_pkg_entities_ihsg_proto_init() {
	if File_pkg_entities_ihsg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_entities_ihsg_proto_rawDesc), len(file_pkg_entities_ihsg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_entities_ihsg_proto_goTypes,
		DependencyIndexes: file_pkg_entities_ihsg_proto_depIdxs,
		MessageInfos:      file_pkg_entities_ihsg_proto_msgTypes,
	}.Build()
	File_pkg_entities_ihsg_proto = out.File
	file_pkg_entities_ihsg_proto_goTypes = nil
	file_pkg_entities_ihsg_proto_depIdxs = nil
}
